server:
  port: 8004

spring:
  application:
    name: cloud-provider-service-zk      #此处的名字,也是被注册进服务的时候的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.entities       #所有Entity别名类所在包